name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      publish_profile:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: restore
        run: npm ci

      - name: build
        run: npm run build -- --mode ${{ inputs.environment }}

      - name: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app_name }}
          publish-profile: ${{ secrets.publish_profile }}
          package: "./dist"
